name: resume_tracker
description: Mobile app for Smart Resume Tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  file_picker: ^5.2.5
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  intl: ^0.18.0
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^8.0.0
  permission_handler: ^10.2.0
  open_file: ^3.2.1
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
